# 3 column families: BASE,ATTRIBUTES,HOURS
USER02.YBUSINESS: CREATE TABLE ‘ USER02.YBUSINESS ’, ‘ BASE ’, ‘ATTRIBUTES’, ‘ HOURS ’

#1 column family: PERHOUR
USER02.YCHECKIN: CREATE TABLE ‘ USER02.YCHECKIN ’, ‘ PERHOUR ’
