SELECT NAME,STATE,STARS
FROM “USER02.YBUSINESS”
WHERE ISOPEN = '1'
ORDER BY NAME DESC LIMIT 1000;

SELECT NAME,ADDRESS,CITY,REVIEWCOUNT
FROM “USER02.YBUSINESS”
WHERE CATEGORIES = 'Drugstores'
ORDER BY REVIEWCOUNT DESC;

SELECT SUM(TO_NUMBER(REVIEWCOUNT)),CATEGORIES
FROM “USER02.YBUSINESS”
WHERE ISOPEN = '1' AND MONDAY != 'None' AND TUESDAY != 'None'
AND WEDNESDAY != 'None' AND THURSDAY != 'None' AND FRIDAY != 'None'
AND SATURDAY != 'None' AND SUNDAY != 'None' AND OPEN24HOURS != 'False'
GROUP BY CATEGORIES
ORDER BY CATEGORIES DESC;

SELECT COUNT(ROWKEY),STATE
FROM “USER02.YBUSINESS”
WHERE SMOKING = 'False' AND SUNDAY != 'None'
GROUP BY STATE;

SELECT SUM(TO_NUMBER(CHECKINS)),WEEKDAY,HOUR
FROM “USER02.YCHECKIN”
WHERE CHECKINS != ‘checkins’
GROUP BY WEEKDAY,HOUR
ORDER BY WEEKDAY DESC, HOUR DESC;

SELECT SUM(TO_NUMBER(CHECKINS)),CATEGORIES
FROM “USER02.YCHECKIN”
JOIN “USER02.YBUSINESS”
ON USER02.YCHECKIN.BUSINESSID = USER02.YBUSINESS.ROWKEY
WHERE ISOPEN = '1'
AND SATURDAY = 'None' AND SUNDAY = 'None'
AND HOUR BETWEEN '14:00' AND '16:00'
GROUP BY CATEGORIES
ORDER BY CATEGORIES DESC;

SELECT NAME,NEIGHBORHOOD,ADDRESS,CITY,
STATE,POSTALCODE,LATITUDE,LONGITUDE,STARS,REVIEWCOUNT,
ISOPEN,CATEGORIES
FROM “USER02.YCHECKIN”
JOIN “USER02.YBUSINESS”
ON USER02.YELPCHECKIN.BUSINESSID=USER02.YELPBUSINESS.ROWKEY
WHERE WEEKDAY = 'Sat'
ORDER BY CHECKINS DESC LIMIT 100;
